# Generated by Django 2.2.5 on 2020-05-31 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Excel_model',
            new_name='Precios_Excel',
        ),
    ]
