# Generated by Django 2.2.5 on 2020-06-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_client', '0002_auto_20200531_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='precios_excel',
            name='nombre',
            field=models.CharField(default='test', max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
