# Generated by Django 2.2.5 on 2020-06-08 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 7, 22, 27, 59, 561778)),
        ),
    ]
