# Generated by Django 2.2.5 on 2020-06-08 04:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0002_auto_20200607_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 7, 22, 30, 48, 231956)),
        ),
        migrations.AlterField(
            model_name='order',
            name='requestor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Profile'),
        ),
    ]
