# Generated by Django 2.2.5 on 2020-06-12 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0003_auto_20200607_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 11, 19, 2, 59, 454041)),
        ),
    ]
