# Generated by Django 2.2.5 on 2020-06-12 01:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0004_auto_20200611_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 12, 1, 35, 44, 895409, tzinfo=utc)),
        ),
    ]
