# Generated by Django 2.2.5 on 2020-06-12 01:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0005_auto_20200611_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 12, 1, 55, 20, 420240, tzinfo=utc)),
        ),
    ]
