# Generated by Django 2.2.5 on 2020-06-12 02:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0007_auto_20200611_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 12, 2, 0, 3, 213691, tzinfo=utc)),
        ),
    ]
