# Generated by Django 2.2.5 on 2020-08-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0010_auto_20200802_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20, verbose_name='Cantidad/Kg'),
        ),
    ]
