# Generated by Django 2.2.5 on 2020-08-23 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0011_auto_20200802_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.CharField(default='No hay comentarios', max_length=200, null=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_order.Status', verbose_name='Estado Orden'),
        ),
    ]
