# Generated by Django 2.2.5 on 2020-05-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unidad_o_kg',
            field=models.CharField(choices=[('kg', 'kg'), ('unidad', 'unidad')], default='kg', max_length=256),
            preserve_default=False,
        ),
    ]
