# Generated by Django 2.2.5 on 2020-08-03 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_auto_20200802_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_product.Category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_product.Measure', verbose_name='Medida'),
        ),
    ]
